<h2>Introduction</h2>
<p>There are many different data types in Python and for beginners it is confusing to remember how to create one or another. Despite that there are a lot of great instructions and articles on this topic, usually they are not bringing all of the data types together.</p>
<p>in this file I try to cover all main data types and compare and remember which types of brackets are used for each of them. </p>

There are four built-in data types in Python used to store collections of data:
<ol><li>list</li> 
    <li>tuple</li>
    <li>set</li>
    <li>dictionary</li>
</ol>
<p>
In addition, there are Numpy arrays and Pandas Dataframes</p>

The type can be specified by a function or by use of a special type of brackets
<br/>
<h2>Bracket types</h2>
There are four main types of brackets: 
<ol type = "1">
    <li>Round brackets <b>"( )"</b> </span></li>
    In British English <span style="background-color:yellow">"Brackets"</span>
    <br>In American English "Parantheses"
<li>Square brackets <b>"[ ]"</b></li>
    In British English "Square Brackets"
    <br>In American English <span style="background-color:yellow">"Brackets"</span>
<li>Curly brackets <b>"{ }"</b></li>
    In British English "Curly brackets"
    <br>In American English "Braces"
</ol>
<br/>
<i>Note, that <b>brackets</b> refer to <u>round brackets</u> in Br.Eng. and to <u>square brackets</u> in Am.Eng.</i>

In [52]:
#type can be defined either by entering function:
list1 = list(("Apple", 10, 0.25))
print(f' this is list1: {list1}')
#or by selecting specific brackets
list2 = ["Apple", 10, 0.25]
print(f' this is list2: {list2}')
#To address an element of a list, its number (starting from zero) in square brackets is used
print(f'first element of a list has number 0 - "list2[0]": {list2[0]}')

 this is list1: ['Apple', 10, 0.25]
 this is list2: ['Apple', 10, 0.25]
first element of a list has number 0 - "list2[0]": Apple


In [21]:
#Elements of the list can be of different types: string, integer, float
#Element of a list can be even a list
list3 = ["Apple", ["Paraguay", 11233], 0.25]
print(f'this is the whole list3: {list3}')
print(f'the second element of the list3 is a list itself: {list3[1]}')
#to get an element of a list which is an element of another list, 
#just add a second index:
print(f''' the second item of the list, which is itself a second item 
      within the main list can be called by: list3[1][1]: {list3[1][1]}''')

this is the whole list3: ['Apple', ['Paraguay', 11233], 0.25]
the second element of the list3 is a list itself: ['Paraguay', 11233]
 the second item of the list, which is itself a second item 
      within the main list can be called by: list3[1][1]: 11233


In [60]:
#Tuples are the list, where elements order is not modifiable, but ordered
tuple1 = tuple(("Apple", 10, 0.25)) #by use of function
tuple2 = ("Apple", 10, 0.25) #by use of round brackets
print(f'tuple1: {tuple1}')
print(f'tuple2: {tuple2}')

#However, call a tulip item by square brackets, like a list item
print(f' second item of a tuple1 is tuple1[1] = {tuple1[1]}')

tuple1: ('Apple', 10, 0.25)
tuple2: ('Apple', 10, 0.25)
 second item of a tuple1 is tuple1[1] = 10


In [48]:
#The difference between the list and the tuple is that the latter is not modifiable. 
#Elements cannot be changed

list2 = ["Apple", 10, 0.25]
#change value of an element can be performed
list4[1] = 12
print(list4)


#The following returns an error: 'tuple' object does not support item assignment
tuple2 = ("Apple", 10, 0.25)
tuple4[1] = 13



NameError: name 'list4' is not defined

In [ ]:
#subset list
list4 = list2[0:2]

In [66]:
#Sets are unordered, unchangable and do not allow duplicates. But the elements can be deleted or added.
#Sets can be created by use of curly brackets "{}"
set1 = {"Apple", "Banana", "Watermelon"}
#Or use a function set()
set2 = set(("Apple", "Banana", "Watermelon"))

print(set1)
print(set2)
#This type can be used as a "drop-down" list to check if the value is in the predefined list
"Apple" in set1

{'Apple', 'Watermelon', 'Banana'}
{'Apple', 'Watermelon', 'Banana'}


True

In [40]:
#Another data type is dictionary
#It is a list of data, but with the key
#Also curly brackets can be used to create a dictionary
dict1 = {"fruit" : "Apple",
        "country" : "Italy",
        "type": "Pink lady"}

#Or use function dict(), but here an equal sign should be used 

dict2 = dict(fruit="Apple",
        country="Italy",
        type="Pink lady")
#Or use dict() and create list [] of tuples (), where the first element is the key and the second is the value
dict3 = dict([("fruit", "Apple"),
        ("country", "Italy"),
        ("type", "Pink lady")])

print(dict1)
print(dict2)
print(dict3)

#the value can be called by a value
print(dict1["fruit"])


#dictionary can contain more than one entry
dict4 = {"fruit" : ["Apple","Peach"],
        "country" : ["Italy", "Spain"],
        "type": ["Pink lady", "White"]}

#Get whole dictionary
print(f'dict4: {dict4}')

#Get all fruits
print(f'dict4, key = fruit: {dict4["fruit"]}')



{'fruit': 'Apple', 'country': 'Italy', 'type': 'Pink lady'}
{'fruit': 'Apple', 'country': 'Italy', 'type': 'Pink lady'}
{'fruit': 'Apple', 'country': 'Italy', 'type': 'Pink lady'}
Apple
dict4: {'fruit': ['Apple', 'Peach'], 'country': ['Italy', 'Spain'], 'type': ['Pink lady', 'White']}
dict4, key = fruit: ['Apple', 'Peach']


KeyError: 1

In [15]:
#Dictionaries can be used to store entries from forms,
#In this case a list of dictionaties is created

#Create a list with 2 dictionaries via dict()
cars1 = list((dict(producer = "Mercedes",
                 model = "CLK320",
                 year = 2003),
            dict(producer = "BMW",
                model = "X5",
                year = 2008)))

print(cars1)

#Or via curly brackets

cars2 = [{"producer": "Mercedes",
                 "model": "CLK320",
                 "year": 2003},
            {"producer":"BMW",
                "model": "X5",
                "year":2008}]

print(cars2)

#Data can be extracted from any dictionary
print(cars2[1]["model"])

#Or even from all dictionaries. 
for i in range(0,2):
    print(cars1[i]["year"])

[{'producer': 'Mercedes', 'model': 'CLK320', 'year': 2003}, {'producer': 'BMW', 'model': 'X5', 'year': 2008}]
[{'producer': 'Mercedes', 'model': 'CLK320', 'year': 2003}, {'producer': 'BMW', 'model': 'X5', 'year': 2008}]
X5
2003
2008


There are two other popular data types, which are not standard in Python, but require a specific package: 
<br>
<ol>
    <li><i>Numpy</i> - based on <b>arrays</b> and used to work with linear algebra and matrices. <a href="https://numpy.org/doc/stable/reference/arrays.ndarray.html">Link</a></li>
    <li><i>Pandas</i> - used for data analysis. The main data type is <b> Dataframe</b> <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html">Link</a></li>
    </ol>

In [13]:
#import package
import numpy as np

#array can be multidimentional and should be of the same type
#create array
array1 = np.array([[1,2,3],[4,5,6],[7,8,9]], np.int32) #matrix 3 * 3

print(array1)

#if matrix contains strings, then numbers also conferted into strings as well
array2 = np.array([[1,2,3],["a","b","c"],[7,8,9]]) #matrix 3 * 3
print(array2)

#the value can be called by sellecting row and column (starting with zero)
print(array1[1,2]) #for second row, third column

print(array1[1,:]) #for whole second row
print(array1[:,2]) #for whole third column

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[['1' '2' '3']
 ['a' 'b' 'c']
 ['7' '8' '9']]
6
[4 5 6]
[3 6 9]


In [1]:
#import package
import pandas as pd

#Before going to Dataframes, another pandas datatype should be presented. 
#Series is onedimentional ndarray with axis labels

#Series can be created form dictionaries 

#dictionary
dict1 = {"fruit" : "Apple",
        "country" : "Italy",
        "sort": "Pink lady"}
print(dict1)

#Series from a dictionary
Series1 = pd.Series(dict1)
print(Series1)


#Keys can be used as indexes in both cases
print(dict1["fruit"])
print(Series1["fruit"])

#Create Series from dictionary with more than 2 values

dict4 = {"fruit" : ["Apple","Peach"],
        "country" : ["Italy", "Spain"],
        "type": ["Pink lady", "White"]}

Series2 = pd.Series(dict4)
print(dict4)
print(Series2["fruit"][1])

{'fruit': 'Apple', 'country': 'Italy', 'sort': 'Pink lady'}
fruit          Apple
country        Italy
sort       Pink lady
dtype: object
Apple
Apple
{'fruit': ['Apple', 'Peach'], 'country': ['Italy', 'Spain'], 'type': ['Pink lady', 'White']}
Peach


In [49]:
# Pandas Dataframe is Two-dimensional, size-mutable, potentially heterogeneous tabular data.
#Dataframe can be created out of arrays, Series

#Create a pandas DataFrame from a dictionay. 
#Keys are converted into columns and values into rows
DataFrame1 = pd.DataFrame(data = dict4, index = ['apple_001','peach_002']) #index defines keys for rows. 

print(f' whole DataFrame1: \n {DataFrame1}\n')

#to get a specific value, method loc() or iloc() or iat() needs to be used
#Select fow
print(f'Dataframe1, first row: \n {DataFrame1.iloc[0]}\n')
#Select column
print(f'Dataframe1, first column (key): \n {DataFrame1.iloc[:,0]}\n')

#Select specific value (row, column)
print(f'\nDataframe1, first row, Second column (key): \n {DataFrame1.iloc[0,1]}\n')


#Select value by index
print(f'Dataframe1, by index (row): \n {DataFrame1.loc["apple_001"]}\n') 

#Select all values by key (column)
print(f'Dataframe1, by key (column): \n {DataFrame1.loc[:,"fruit"]}\n') 



 whole DataFrame1: 
            fruit country       type
apple_001  Apple   Italy  Pink lady
peach_002  Peach   Spain      White

Dataframe1, first row: 
 fruit          Apple
country        Italy
type       Pink lady
Name: apple_001, dtype: object

Dataframe1, first column (key): 
 apple_001    Apple
peach_002    Peach
Name: fruit, dtype: object


Dataframe1, first row, Second column (key): 
 Italy

Dataframe1, by index (row): 
 fruit          Apple
country        Italy
type       Pink lady
Name: apple_001, dtype: object

Dataframe1, by key (column): 
 apple_001    Apple
peach_002    Peach
Name: fruit, dtype: object



<h2>Conclusion</h2>
<p>In this exercise, I went through all main python data types and applied basic functionality to create, call, change data objects. From my point of view, comparison of different data types formating (brackets) helps to learn them more efficiently and systematised.</p> 

